import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter, Oswald } from "next/font/google";
import Footer from "@/components/Footer";
import PlanProvider from "@/context/PlanProvider";
import { ToastContainer } from "react-toastify";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const oswald = Oswald({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-oswald",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${oswald.variable}`}>
      <body className="min-h-full flex flex-col">
        <PlanProvider>
          <Navbar />
          {children}
          <Footer />
          <ToastContainer />
        </PlanProvider>
      </body>
    </html>
  );
}
